package github

import (
	"errors"
	"net/url"
	"strings"

	"github.com/stainedhead/agent-okta-d/internal/domain"
)

// ShellQuote single-quotes s for a POSIX shell.
func ShellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// EnvLines renders the `env github` output (GH-4): export lines for the gh CLI.
// For github.com it sets GH_TOKEN; for another API base (GHES, *.ghe.com) it
// sets GH_ENTERPRISE_TOKEN and GH_HOST instead, which is what gh reads there.
func EnvLines(token domain.SecretString, apiBase string) (string, error) {
	t := token.Reveal()
	if t == "" {
		return "", domain.Wrap(domain.ErrProvider, errors.New("empty github token"))
	}
	if strings.ContainsAny(t, "\r\n\x00") {
		return "", domain.Wrap(domain.ErrProvider, errors.New("github token contains a control character"))
	}
	if apiBase == "" || apiBase == DefaultAPIBase || apiBase == DefaultAPIBase+"/" {
		return "export GH_TOKEN=" + ShellQuote(t) + "\n", nil
	}
	host := ""
	if u, err := url.Parse(WebBase(apiBase)); err == nil {
		host = u.Host
	}
	out := "export GH_ENTERPRISE_TOKEN=" + ShellQuote(t) + "\n"
	if host != "" {
		out += "export GH_HOST=" + ShellQuote(host) + "\n"
	}
	return out, nil
}

// ShimScript returns the `gh` shim (GH-4): it asks the daemon for the token per
// invocation, exports GH_TOKEN and execs the real gh, so `gh auth login` is
// never needed and no token lands in gh's own config. It fails closed when the
// daemon cannot supply a token. agentBin and realGh are absolute paths.
func ShimScript(agentBin, realGh string) (string, error) {
	for name, p := range map[string]string{"agent-okta-d path": agentBin, "gh path": realGh} {
		if p == "" || strings.ContainsAny(p, "\r\n\x00") {
			return "", domain.NewConfigError(name, "must be a non-empty single-line path")
		}
	}
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by agent-okta-d configure gh. Do not edit.\n")
	b.WriteString("GH_TOKEN=$(" + ShellQuote(agentBin) + " token github --format raw) || {\n")
	b.WriteString("  echo \"gh shim: could not obtain a github credential from agent-okta-d\" >&2\n")
	b.WriteString("  exit 1\n}\n")
	b.WriteString("[ -n \"$GH_TOKEN\" ] || { echo \"gh shim: empty github credential\" >&2; exit 1; }\n")
	b.WriteString("export GH_TOKEN\n")
	b.WriteString("exec " + ShellQuote(realGh) + " \"$@\"\n")
	return b.String(), nil
}
